import { FormEvent, useEffect, useRef, useState } from "react";
import { HiOutlineCheck, HiOutlineEllipsisHorizontal, HiOutlineMicrophone, HiOutlinePaperAirplane, HiOutlinePause, HiOutlineSpeakerWave, HiOutlineSpeakerXMark, HiOutlineXMark } from "react-icons/hi2";
import ReactMarkdown from "react-markdown";
import { agentApi } from "./api";
import type { AgentApproval, AgentKind, AgentMessage, AgentSnapshot, AgentStatus } from "./types";

type Drawer = "tasks"|"approvals"|"activity"|"integrations"|"settings"|null;
type Props={agent:AgentKind;legacyData:unknown;onLegacyMigrated:()=>void};
const labels={learning:{name:"Mentor",headline:"What do you want to learn?",prompt:"Build a plan, teach a concept, review my work, or schedule practice."},career:{name:"Career",headline:"What should we move forward?",prompt:"Find opportunities, prepare an application, track a reply, or plan a follow-up."}};

function blobToBase64(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.readAsDataURL(blob);});}
function statusLabel(status:AgentStatus){return ({idle:"Ready",listening:"Listening",thinking:"Thinking",working:"Working",approval:"Approval needed",complete:"Complete",error:"Needs attention"})[status];}

export default function AgentWorkspace({agent,legacyData,onLegacyMigrated}:Props){
  const [snapshot,setSnapshot]=useState<AgentSnapshot|null>(null),[conversationId,setConversationId]=useState(""),[messages,setMessages]=useState<AgentMessage[]>([]);
  const [message,setMessage]=useState(""),[status,setStatus]=useState<AgentStatus>("idle"),[drawer,setDrawer]=useState<Drawer>(null),[menuOpen,setMenuOpen]=useState(false),[error,setError]=useState("");
  const [speaking,setSpeaking]=useState(true),[recording,setRecording]=useState(false),runRef=useRef(""),recorderRef=useRef<MediaRecorder|null>(null),chunksRef=useRef<Blob[]>([]),audioRef=useRef<HTMLAudioElement|null>(null);
  const copy=labels[agent];
  async function refresh(){const next=await agentApi.snapshot(agent);setSnapshot(next);if(next.approvals.some((item)=>item.status==="pending"))setStatus("approval");return next;}
  async function loadConversation(id:string){const result=await agentApi.conversation(agent,id);setMessages(result.conversation.messages);}
  useEffect(()=>{let disposed=false;(async()=>{try{await agentApi.migrate(agent,legacyData);if(disposed)return;onLegacyMigrated();const conversations=await agentApi.conversations(agent);const current=conversations.conversations[0]||(await agentApi.createConversation(agent)).conversation;if(disposed)return;setConversationId(current.id);await Promise.all([loadConversation(current.id),refresh()]);}catch(value){if(!disposed){setError(value instanceof Error?value.message:"Agent could not load.");setStatus("error");}}})();return()=>{disposed=true;};},[agent]);
  useEffect(()=>{if(!conversationId)return;let cursor=0;const events=new EventSource(`/api/agents/${agent}/events?after=${cursor}`);events.onmessage=async(event)=>{cursor=Number(event.lastEventId||cursor);const payload=JSON.parse(event.data);if(payload.type==="running"){setStatus("working");return;}if(["completed","failed","awaiting_approval","approval_required","cancelled"].includes(payload.type)){await Promise.all([loadConversation(conversationId),refresh()]);if(payload.type==="failed")setStatus("error");else if(payload.type.includes("approval"))setStatus("approval");else setStatus("complete");if(payload.data?.answer&&speaking)void speak(String(payload.data.answer));}};return()=>events.close();},[agent,conversationId,speaking]);
  async function submit(event:FormEvent){event.preventDefault();const text=message.trim();if(!text||!conversationId)return;setMessage("");setMessages((items)=>[...items,{id:crypto.randomUUID(),role:"user",content:text}]);setStatus("thinking");setError("");try{const run=await agentApi.message(agent,conversationId,text);runRef.current=run.runId;}catch(value){setError(value instanceof Error?value.message:"The task could not start.");setStatus("error");}}
  async function speak(text:string){try{const result=await agentApi.speak(text.slice(0,4000));audioRef.current?.pause();audioRef.current=new Audio(`data:${result.mimeType};base64,${result.audioBase64}`);await audioRef.current.play();}catch{/* Text remains available when speech is unavailable. */}}
  async function toggleRecording(){if(recording){recorderRef.current?.stop();return;}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setError("Voice recording is not supported in this browser.");return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const recorder=new MediaRecorder(stream);chunksRef.current=[];recorder.ondataavailable=(event)=>{if(event.data.size)chunksRef.current.push(event.data);};recorder.onstop=async()=>{setRecording(false);setStatus("thinking");stream.getTracks().forEach((track)=>track.stop());try{const blob=new Blob(chunksRef.current,{type:recorder.mimeType||"audio/webm"});const result=await agentApi.transcribe(await blobToBase64(blob),blob.type);setMessage(result.transcript);setStatus("idle");}catch(value){setError(value instanceof Error?value.message:"The recording could not be transcribed.");setStatus("error");}};recorderRef.current=recorder;recorder.start();setRecording(true);setStatus("listening");}catch{setError("Microphone access was not granted.");setStatus("error");}}
  async function decide(approval:AgentApproval,decision:"approve"|"reject"){try{setStatus("working");await agentApi.decide(approval.id,decision);await refresh();setStatus("complete");}catch(value){setError(value instanceof Error?value.message:"The approval could not be completed.");setStatus("error");}}
  async function connectGoogle(){try{const {authorizationUrl}=await agentApi.connectGoogle();window.location.assign(authorizationUrl);}catch(value){setError(value instanceof Error?value.message:"Google could not be connected.");setStatus("error");}}
  const pending=snapshot?.approvals.filter((item)=>item.status==="pending")||[];
  return <section className={`agent-workspace agent-${agent}`} aria-label={`${copy.name} agent`}>
    <div className="agent-minimal-menu"><button type="button" aria-label="Agent menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen((value)=>!value)}><HiOutlineEllipsisHorizontal /></button>{menuOpen&&<div role="menu">{(["tasks","approvals","activity","integrations","settings"] as const).map((item)=><button type="button" role="menuitem" key={item} onClick={()=>{setDrawer(item);setMenuOpen(false);}}>{item[0].toUpperCase()+item.slice(1)}{item==="approvals"&&pending.length>0?<span>{pending.length}</span>:null}</button>)}</div>}</div>
    <div className="agent-stage">
      <button type="button" className={`agent-orb agent-orb-${status}`} aria-label={`${copy.name} agent: ${statusLabel(status)}`} onClick={()=>document.getElementById(`${agent}-agent-input`)?.focus()}><span className="agent-orb-core"/><span className="agent-orb-ring"/><span className="agent-orb-shimmer"/></button>
      <p className="agent-status" aria-live="polite"><i/>{copy.name} · {statusLabel(status)}</p>
      <h2>{copy.headline}</h2>
      <p className="agent-prompt">{copy.prompt}</p>
      {messages.length>0&&<div className="agent-transcript" aria-label="Recent conversation">{messages.slice(-4).map((item)=><div key={item.id} className={`workspace-agent-message workspace-agent-message-${item.role}`}><strong>{item.role==="user"?"You":copy.name}</strong>{item.role==="assistant"?<ReactMarkdown>{item.content}</ReactMarkdown>:<p>{item.content}</p>}</div>)}</div>}
      {error&&<p className="agent-error" role="alert">{error}</p>}
      <form className="agent-composer" onSubmit={submit}><button type="button" className={recording?"recording":""} aria-label={recording?"Stop recording":"Push to talk"} onClick={toggleRecording}>{recording?<HiOutlinePause/>:<HiOutlineMicrophone/>}</button><input id={`${agent}-agent-input`} value={message} onChange={(event)=>setMessage(event.target.value)} placeholder={`Talk to ${copy.name}…`} maxLength={8000}/><button type="button" aria-label={speaking?"Disable spoken replies":"Enable spoken replies"} onClick={()=>setSpeaking((value)=>!value)}>{speaking?<HiOutlineSpeakerWave/>:<HiOutlineSpeakerXMark/>}</button>{runRef.current&&["thinking","working"].includes(status)?<button type="button" aria-label="Cancel current task" onClick={async()=>{await agentApi.cancel(runRef.current);setStatus("idle");}}><HiOutlineXMark/></button>:<button type="submit" aria-label="Send message" disabled={!message.trim()}><HiOutlinePaperAirplane/></button>}</form>
      {snapshot?.tasks.some((task)=>["queued","running","scheduled","awaiting_approval"].includes(task.state))&&<button type="button" className="agent-task-indicator" onClick={()=>setDrawer("tasks")}>Active work <span>{snapshot.tasks.filter((task)=>["queued","running","scheduled","awaiting_approval"].includes(task.state)).length}</span></button>}
    </div>
    {drawer&&<div className="agent-panel-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget)setDrawer(null);}}><aside className="agent-panel" aria-label={`${drawer} drawer`}><header><div><p className="kicker">{copy.name}</p><h3>{drawer[0].toUpperCase()+drawer.slice(1)}</h3></div><button type="button" aria-label="Close drawer" onClick={()=>setDrawer(null)}><HiOutlineXMark/></button></header>
      {drawer==="tasks"&&<div className="agent-list">{snapshot?.tasks.length?snapshot.tasks.map((task)=><article key={task.id}><span className={`agent-state agent-state-${task.state}`}>{task.state.replace("_"," ")}</span><strong>{task.title}</strong><small>{new Date(task.updatedAt).toLocaleString()}</small></article>):<p>No tasks yet.</p>}</div>}
      {drawer==="approvals"&&<div className="agent-list">{snapshot?.approvals.length?snapshot.approvals.map((approval)=><article key={approval.id} className="approval-card"><span className={`agent-state agent-state-${approval.status}`}>{approval.status}</span><strong>{approval.summary}</strong><small>{approval.actionType==="gmail.create_draft"?"Creates a Gmail draft. It will not send.":approval.actionType==="calendar.create_event"?"Creates an event in your Google Calendar.":"External action"}</small>{approval.status==="pending"&&<div><button type="button" onClick={()=>decide(approval,"reject")}><HiOutlineXMark/> Reject</button><button type="button" onClick={()=>decide(approval,"approve")}><HiOutlineCheck/> Approve</button></div>}</article>):<p>No approvals yet.</p>}</div>}
      {drawer==="activity"&&<div className="agent-list">{snapshot?.records.length?snapshot.records.map((record)=><article key={record.id}><span className="agent-state">{record.recordType.replace("_"," ")}</span><strong>{record.title}</strong><small>{record.status}</small></article>):<p>Agent-created plans, opportunities, lessons, and evidence will appear here.</p>}</div>}
      {drawer==="integrations"&&<div className="agent-integrations"><article><div><strong>Google Workspace</strong><small>{snapshot?.connected.some((item)=>item.provider==="google")?snapshot.connected.find((item)=>item.provider==="google")?.accountLabel:"Calendar scheduling, Gmail reply tracking, and approved drafts"}</small></div>{snapshot?.connected.some((item)=>item.provider==="google")?<button type="button" onClick={async()=>{await agentApi.disconnectGoogle();await refresh();}}>Disconnect</button>:<button type="button" onClick={connectGoogle}>Connect</button>}</article><p>LinkedIn, Fiverr, Canvas, and Moodle remain tracked sources or supervised handoffs until an approved user-side API is available.</p></div>}
      {drawer==="settings"&&<div className="agent-settings"><label><span>Daily run limit</span><input type="number" min="1" max="100" value={Number(snapshot?.policy.dailyRunLimit||25)} onChange={(event)=>setSnapshot((current)=>current?{...current,policy:{...current.policy,dailyRunLimit:Number(event.target.value)}}:current)}/></label><label><span>Require approval for every external action</span><input type="checkbox" checked readOnly/></label><button type="button" onClick={async()=>{if(snapshot){await agentApi.updatePolicy(agent,snapshot.policy);await refresh();}}}>Save settings</button><details><summary>Migrated profile</summary><pre>{JSON.stringify(snapshot?.profile||{},null,2)}</pre></details></div>}
    </aside></div>}
  </section>;
}
