import { useState } from "react";
import type { ProjectColumnType, ProjectFlowchart, ProjectMindmap, ProjectTable } from "./model";

const id = (prefix: string) => `${prefix}-${globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`}`;

export function ProjectTableEditor({ table, onChange }: { table: ProjectTable; onChange: (table: ProjectTable) => void }) {
  const [name, setName] = useState("");
  const [type, setType] = useState<ProjectColumnType>("text");
  const [options, setOptions] = useState("");
  const updateCell = (rowId: string, columnId: string, value: string | boolean) => onChange({ ...table, rows: table.rows.map((row) => row.id === rowId ? { ...row, cells: { ...row.cells, [columnId]: value } } : row) });
  const deleteColumn = (columnId: string) => {
    if (table.columns.length === 1 || !window.confirm("Delete this column and its values?")) return;
    onChange({ columns: table.columns.filter((column) => column.id !== columnId), rows: table.rows.map((row) => { const cells = { ...row.cells }; delete cells[columnId]; return { ...row, cells }; }) });
  };
  return <section className="project-mode-surface project-table-mode" aria-label="Project table">
    <header><h3>Table</h3><button type="button" onClick={() => onChange({ ...table, rows: [...table.rows, { id: id("row"), cells: {} }] })}>+ Row</button></header>
    <form className="project-table-column-form" onSubmit={(event) => { event.preventDefault(); const trimmed = name.trim(); if (!trimmed) return; onChange({ ...table, columns: [...table.columns, { id: id("column"), name: trimmed, type, ...(type === "select" ? { options: options.split(",").map((item) => item.trim()).filter(Boolean) } : {}) }] }); setName(""); setOptions(""); }}>
      <input aria-label="New project column name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Column name" />
      <select aria-label="New project column type" value={type} onChange={(event) => setType(event.target.value as ProjectColumnType)}>{(["text", "number", "date", "checkbox", "select"] as const).map((item) => <option key={item} value={item}>{item}</option>)}</select>
      {type === "select" && <input aria-label="Project select options" value={options} onChange={(event) => setOptions(event.target.value)} placeholder="Todo, Doing, Done" />}
      <button type="submit" disabled={!name.trim()}>Add column</button>
    </form>
    <div className="project-table-scroll"><table><thead><tr>{table.columns.map((column) => <th key={column.id}><input aria-label={`Project column ${column.name}`} value={column.name} onChange={(event) => onChange({ ...table, columns: table.columns.map((item) => item.id === column.id ? { ...item, name: event.target.value } : item) })} /><button type="button" aria-label={`Delete ${column.name} column`} disabled={table.columns.length === 1} onClick={() => deleteColumn(column.id)}>×</button></th>)}<th>Actions</th></tr></thead><tbody>{table.rows.map((row, rowIndex) => <tr key={row.id}>{table.columns.map((column) => <td key={column.id}>{column.type === "checkbox" ? <input type="checkbox" aria-label={`${column.name} row ${rowIndex + 1}`} checked={row.cells[column.id] === true} onChange={(event) => updateCell(row.id, column.id, event.target.checked)} /> : column.type === "select" ? <select aria-label={`${column.name} row ${rowIndex + 1}`} value={String(row.cells[column.id] ?? "")} onChange={(event) => updateCell(row.id, column.id, event.target.value)}><option value="">Select…</option>{column.options?.map((option) => <option key={option}>{option}</option>)}</select> : <input type={column.type} aria-label={`${column.name} row ${rowIndex + 1}`} value={String(row.cells[column.id] ?? "")} onChange={(event) => updateCell(row.id, column.id, event.target.value)} />}</td>)}<td><button type="button" aria-label={`Delete project row ${rowIndex + 1}`} onClick={() => window.confirm("Delete this row?") && onChange({ ...table, rows: table.rows.filter((item) => item.id !== row.id) })}>×</button></td></tr>)}</tbody></table></div>
  </section>;
}

export function ProjectFlowchartEditor({ flowchart, onChange }: { flowchart: ProjectFlowchart; onChange: (flowchart: ProjectFlowchart) => void }) {
  const [source, setSource] = useState("");
  const nodeIds = new Set(flowchart.nodes.map((node) => node.id));
  const edges = flowchart.edges.filter((edge) => nodeIds.has(edge.source) && nodeIds.has(edge.target));
  const removeNode = (nodeId: string) => onChange({ ...flowchart, nodes: flowchart.nodes.filter((node) => node.id !== nodeId), edges: flowchart.edges.filter((edge) => edge.source !== nodeId && edge.target !== nodeId) });
  return <section className="project-mode-surface" aria-label="Project flowchart">
    <header><h3>Flowchart</h3><div><button type="button" onClick={() => onChange({ ...flowchart, nodes: [...flowchart.nodes, { id: id("node"), label: `Node ${flowchart.nodes.length + 1}`, x: 40 + flowchart.nodes.length * 45, y: 50 + flowchart.nodes.length * 35, color: "#38bdf8" }] })}>+ Node</button><button type="button" onClick={() => onChange({ ...flowchart, zoom: Math.max(0.5, flowchart.zoom - 0.1) })}>−</button><button type="button" onClick={() => onChange({ ...flowchart, zoom: Math.min(1.75, flowchart.zoom + 0.1) })}>+</button><button type="button" onClick={() => onChange({ ...flowchart, zoom: 1 })}>Fit</button></div></header>
    <p className="project-map-hint">Type inside a rectangle, then click Connect on two nodes to draw an arrow.</p>
    <div className="project-flow-canvas" aria-label="Flowchart canvas"><div style={{ transform: `scale(${flowchart.zoom})` }}>{edges.map((edge) => { const from = flowchart.nodes.find((node) => node.id === edge.source)!; const to = flowchart.nodes.find((node) => node.id === edge.target)!; const left = from.x + 65, top = from.y + 30, width = Math.hypot(to.x - from.x, to.y - from.y), angle = Math.atan2(to.y - from.y, to.x - from.x) * 180 / Math.PI; return <button type="button" className="project-flow-edge" key={edge.id} aria-label={`Delete connection ${from.label} to ${to.label}`} style={{ left, top, width, transform: `rotate(${angle}deg)` }} onClick={() => onChange({ ...flowchart, edges: edges.filter((item) => item.id !== edge.id) })} />; })}{flowchart.nodes.map((node) => <article key={node.id} className={`project-flow-node ${source === node.id ? "connecting" : ""}`} style={{ left: node.x, top: node.y, borderColor: node.color }} draggable onDragEnd={(event) => { const canvas = event.currentTarget.parentElement?.parentElement?.getBoundingClientRect(); if (!canvas) return; onChange({ ...flowchart, nodes: flowchart.nodes.map((item) => item.id === node.id ? { ...item, x: Math.max(0, (event.clientX - canvas.left) / flowchart.zoom), y: Math.max(0, (event.clientY - canvas.top) / flowchart.zoom) } : item) }); }}><input aria-label={`${node.label} label`} value={node.label} onChange={(event) => onChange({ ...flowchart, nodes: flowchart.nodes.map((item) => item.id === node.id ? { ...item, label: event.target.value } : item) })} /><input type="color" aria-label={`${node.label} color`} value={node.color} onChange={(event) => onChange({ ...flowchart, nodes: flowchart.nodes.map((item) => item.id === node.id ? { ...item, color: event.target.value } : item) })} /><button type="button" aria-label={`Connect ${node.label}`} className="project-node-connect" onClick={() => { if (!source) { setSource(node.id); return; } if (source !== node.id && !edges.some((edge) => edge.source === source && edge.target === node.id)) onChange({ ...flowchart, edges: [...edges, { id: id("edge"), source, target: node.id, label: "" }] }); setSource(""); }}>{source === node.id ? "Selected" : "Connect"}</button><button type="button" aria-label={`Delete ${node.label}`} onClick={() => removeNode(node.id)}>×</button></article>)}</div></div>
  </section>;
}

export function ProjectMindmapEditor({ mindmap, onChange }: { mindmap: ProjectMindmap; onChange: (mindmap: ProjectMindmap) => void }) {
  const [source, setSource] = useState("");
  const validIds = new Set(mindmap.objects.map((object) => object.id));
  const objects = mindmap.objects.map((object) => ({ ...object, parentId: object.parentId && validIds.has(object.parentId) && object.parentId !== object.id ? object.parentId : undefined, relationIds: object.relationIds.filter((relationId) => validIds.has(relationId) && relationId !== object.id) }));
  const removeObject = (objectId: string) => onChange({ objects: objects.filter((object) => object.id !== objectId).map((object) => ({ ...object, parentId: object.parentId === objectId ? undefined : object.parentId, relationIds: object.relationIds.filter((id) => id !== objectId) })) });
  const links = objects.flatMap((object) => [
    ...(object.parentId ? [{ id: `parent-${object.id}`, source: object.parentId, target: object.id, kind: "parent" }] : []),
    ...object.relationIds.map((target) => ({ id: `relation-${object.id}-${target}`, source: object.id, target, kind: "relation" })),
  ]).filter((link, index, all) => all.findIndex((candidate) => candidate.source === link.source && candidate.target === link.target && candidate.kind === link.kind) === index);
  return <section className="project-mode-surface" aria-label="Project mindmap">
    <header><h3>Object mindmap</h3><button type="button" onClick={() => onChange({ objects: [...objects, { id: id("object"), title: "", x: 60 + (objects.length % 3) * 250, y: 60 + Math.floor(objects.length / 3) * 180, color: "#38bdf8", relationIds: [], fields: [] }] })}>+ Idea</button></header>
    <p className="project-map-hint">Type inside a rectangle, then click Connect on two ideas to draw an arrow.</p>
    <div className="project-flow-canvas project-mindmap-canvas" aria-label="Mindmap canvas"><div>
      {links.map((link) => { const from = objects.find((object) => object.id === link.source); const to = objects.find((object) => object.id === link.target); if (!from || !to) return null; const fromName = from.title.trim() || `Idea ${objects.indexOf(from) + 1}`; const toName = to.title.trim() || `Idea ${objects.indexOf(to) + 1}`; const left = from.x + 110, top = from.y + 45, width = Math.hypot(to.x - from.x, to.y - from.y), angle = Math.atan2(to.y - from.y, to.x - from.x) * 180 / Math.PI; return <div aria-label={`${link.kind === "parent" ? "Parent" : "Relation"} arrow ${fromName} to ${toName}`} className={`project-flow-edge project-mindmap-edge ${link.kind}`} key={link.id} style={{ left, top, width, transform: `rotate(${angle}deg)` }} />; })}
      {objects.map((object, objectIndex) => { const objectName = object.title.trim() || `Idea ${objectIndex + 1}`; return <article key={object.id} className={`project-flow-node project-mindmap-node ${source === object.id ? "connecting" : ""}`} style={{ left: object.x, top: object.y, borderColor: object.color }} draggable onDragEnd={(event) => { const canvas = event.currentTarget.parentElement?.parentElement?.getBoundingClientRect(); if (!canvas) return; onChange({ objects: objects.map((item) => item.id === object.id ? { ...item, x: Math.max(0, event.clientX - canvas.left), y: Math.max(0, event.clientY - canvas.top) } : item) }); }}>
        <div className="project-mindmap-node-head"><input aria-label={`${objectName} title`} value={object.title} placeholder="Type an idea…" onChange={(event) => onChange({ objects: objects.map((item) => item.id === object.id ? { ...item, title: event.target.value } : item) })} /><input type="color" aria-label={`${objectName} color`} value={object.color} onChange={(event) => onChange({ objects: objects.map((item) => item.id === object.id ? { ...item, color: event.target.value } : item) })} /><button type="button" aria-label={`Delete ${objectName}`} onClick={() => removeObject(object.id)}>×</button></div>
        <button type="button" className="project-node-connect" aria-label={`Connect ${objectName}`} onClick={() => { if (!source) { setSource(object.id); return; } if (source !== object.id) onChange({ objects: objects.map((item) => item.id === source && !item.relationIds.includes(object.id) ? { ...item, relationIds: [...item.relationIds, object.id] } : item) }); setSource(""); }}>{source === object.id ? "Selected — choose another idea" : "Connect"}</button>
        {object.relationIds.length > 0 && <div className="project-mindmap-links">{object.relationIds.map((relationId) => <button type="button" key={relationId} onClick={() => onChange({ objects: objects.map((item) => item.id === object.id ? { ...item, relationIds: item.relationIds.filter((candidate) => candidate !== relationId) } : item) })}>× {objects.find((item) => item.id === relationId)?.title.trim() || "Untitled idea"}</button>)}</div>}
      </article>; })}
    </div></div>
  </section>;
}
